use anyhow::Result;
use chrono::{Datelike, NaiveDate};
use serde::{Deserialize, Serialize};
use crate::client::CurbyClient;
use crate::engine::SimulationSession;
use crate::tools::astronomy::get_solar_term;
use crate::tools::san_he::{analyze_san_he, SanHeAnalysis};
use crate::tools::qimen::{calculate_qimen, QiMenChart};
use crate::tools::chinese_meta::{get_stem, get_branch};

/// Configuration for a Feng Shui analysis session.
///
/// This struct aggregates all user inputs required to perform a comprehensive
/// Metaphysical analysis, including Flying Stars, BaZi, and Quantum simulations.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct FengShuiConfig {
    /// Birth Year (e.g., 1980) for BaZi and Kua calculation.
    pub birth_year: Option<i32>,
    /// Birth Month (1-12).
    pub birth_month: Option<u32>,
    /// Birth Day (1-31).
    pub birth_day: Option<u32>,
    /// Birth Hour (0-23) for Pillar calculation.
    pub birth_hour: Option<u32>,
    /// Gender ("M" or "F") for Kua number calculation.
    pub gender: Option<String>,
    /// Year the building was constructed (determines the Period).
    pub construction_year: i32,
    /// Magnetic compass reading of the house facing direction (0.0 - 359.9).
    pub facing_degrees: f64,
    /// Year for the Annual Star chart (defaults to current system year).
    pub current_year: Option<i32>,
    /// Month for the Monthly Star chart.
    pub current_month: Option<u32>,
    /// Day for the Daily Star chart.
    pub current_day: Option<u32>,
    /// User's specific intention (e.g., "Wealth", "Love") for Quantum Resonance checks.
    pub intention: Option<String>,
    /// If true, enables Quantum Entropy mutations in the chart generation.
    pub quantum_mode: bool,
    /// List of user-placed cures on the virtual grid.
    pub virtual_cures: Option<Vec<VirtualCure>>,
}

/// Represents a "Virtual Cure" placed on the frontend grid.
///
/// Used to simulate the energetic impact of objects (e.g., "Metal Wu Lou")
/// on the Qi Flow heatmap.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct VirtualCure {
    pub name: String,
    pub x: f64, // Grid normalized coordinates (0.0-3.0)
    pub y: f64,
}

/// The complete report generated by the system.
///
/// This includes all sub-modules: BaZi, Kua, Flying Stars, and Quantum Analysis.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct FengShuiReport {
    pub bazi: Option<BaZiProfile>,
    pub kua: Option<KuaProfile>,
    pub house_kua: Option<KuaProfile>,
    pub hexagram: Option<HexagramInfo>,
    pub annual_chart: FlyingStarChart,
    pub replacement_chart: Option<FlyingStarChart>,
    pub yearly_afflictions: Vec<String>,
    pub monthly_chart: Option<FlyingStarChart>,
    pub daily_chart: Option<FlyingStarChart>,
    pub formations: Vec<String>,
    pub quantum: QuantumAnalysis,
    pub advice: Vec<String>,
    pub san_he: Option<SanHeAnalysis>,
    pub qimen: Option<QiMenChart>,
    pub period_9_compliance: Vec<String>,
}

#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct HexagramInfo {
    pub name: String,
    pub index: usize,
    pub meaning: String,
    pub element: String,
}

/// Represents the Four Pillars of Destiny (BaZi) for the user.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct BaZiProfile {
    pub year_pillar: String,
    pub month_pillar: String,
    pub day_pillar: String,
    pub hour_pillar: String,
    pub day_master: String,
    pub favorable_elements: Vec<String>,
    pub quantum_flux: Option<String>, // Real-time elemental strength amplified by quantum noise.
    pub alternate_pillars: Option<Vec<String>>, // Probabilistic "alternate timeline" pillars.
}

/// Represents the Eight Mansions (Ba Zhai) Kua profile.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct KuaProfile {
    pub number: i32,
    pub group: String, // "East Group" or "West Group"
    pub element: String,
    pub lucky_directions: Vec<(String, String)>, // (Direction, Name e.g. "Sheng Chi")
}

/// Represents a full 9-grid Flying Star chart.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct FlyingStarChart {
    pub period: i32,
    pub label: String,
    pub facing_mountain: String,
    pub sitting_mountain: String,
    pub palaces: Vec<Palace>,
}

/// A single sector (Palace) within the Flying Star chart.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct Palace {
    pub sector: String, // e.g., "NW", "Center"
    pub base_star: i32, // Period Star
    pub mountain_star: i32, // Sitting Star (Health/Relationships)
    pub water_star: i32, // Facing Star (Wealth/Career)
    pub visiting_star: i32, // Annual/Monthly star
}

/// Analysis derived from Quantum Entropy simulations.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct QuantumAnalysis {
    pub volatility_index: f64, // 0.0 - 1.0 Measure of entropy chaos
    pub focus_sector: String, // The sector "chosen" by the quantum decision tree
    pub anomalies: Vec<String>, // Statistical outliers found in simulation
    pub intention_resonance: Option<String>,
    pub suggested_cures: Vec<CureSuggestion>,
    pub qi_flow: Option<QiFlowAnalysis>,
    pub qi_heatmap: Option<Vec<Vec<f64>>>, // 3x3 Heatmap for frontend visualization
    pub cure_efficacy: Option<f64>, // Simulated impact of virtual cures
}

#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct CureSuggestion {
    pub sector: String,
    pub affliction: String,
    pub cure_name: String,
    pub placement_location: String,
    pub success_probability: f64,
}

#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct QiFlowAnalysis {
    pub flow_path: Vec<String>,
    pub blockages: Vec<String>,
}

// === MAIN ENTRY POINTS ===

/// CLI Entry Point (Deprecated, now defaults to Server)
pub async fn run_feng_shui_cli() -> Result<()> {
    println!("=== QUANTUM FENG SHUI & FLYING STARS SYSTEM (EXPANDED) ===");
    Ok(())
}

/// Core Logic Handler (Shared by CLI and Server).
///
/// This function orchestrates the entire analysis pipeline:
/// 1. Fetches Quantum Entropy.
/// 2. Calculates Traditional Charts (BaZi, Kua, Flying Stars).
/// 3. Injects Quantum Entropy for mutations and probabilistic analysis.
/// 4. Aggregates results into a comprehensive report.
pub async fn generate_report(config: FengShuiConfig) -> Result<FengShuiReport> {
    // 1. Initialize Quantum Source
    let mut client = CurbyClient::new();
    // Fetch 4KB of true randomness to seed simulations
    let entropy = client.fetch_bulk_randomness(4096).await?;
    let session = SimulationSession::new(entropy);

    // 2. BaZi Calculation (with Solar Terms and Quantum Mode)
    let bazi_profile = if let (Some(y), Some(m), Some(d)) = (config.birth_year, config.birth_month, config.birth_day) {
        match calculate_bazi(y, m, d, config.birth_hour.unwrap_or(12), if config.quantum_mode { Some(&session) } else { None }) {
            Ok(profile) => Some(profile),
            Err(_) => None,
        }
    } else { None };

    // 3. Personal Kua Calculation
    let kua_profile = if let (Some(y), Some(g)) = (config.birth_year, &config.gender) {
        Some(calculate_kua_profile(y, g))
    } else { None };

    // 4. House Kua (Sitting) and Hexagram (Facing)
    let sitting_deg = (config.facing_degrees + 180.0) % 360.0;
    let house_kua = Some(calculate_house_kua(sitting_deg));
    let hexagram = Some(calculate_hexagram(config.facing_degrees));

    // 5. Time Configuration
    let current_year = config.current_year.unwrap_or_else(|| chrono::Local::now().year());
    let current_month = config.current_month.unwrap_or_else(|| chrono::Local::now().month());
    let current_day = config.current_day.unwrap_or_else(|| chrono::Local::now().day());

    // 6. Flying Star Chart Generation
    // If quantum_mode is on, stars may "mutate" (flip polarity) based on entropy.
    let mutation_source = if config.quantum_mode { Some(&session) } else { None };

    let annual_chart = calculate_flying_star_chart(config.construction_year, config.facing_degrees, current_year, mutation_source);
    let replacement_chart = calculate_replacement_chart(config.construction_year, config.facing_degrees, current_year, mutation_source);
    let yearly_afflictions = calculate_yearly_afflictions(current_year, config.facing_degrees);
    let monthly_chart = calculate_monthly_chart(current_year, current_month, mutation_source);
    let daily_chart = calculate_daily_chart(current_year, current_month, current_day, mutation_source);

    // 7. Analysis & Pattern Detection
    let formations = analyze_formations(&annual_chart);

    // 8. Quantum Simulation (Qi Flow, Heatmaps, Cures)
    let quantum = run_quantum_analysis(&session, &annual_chart, monthly_chart.as_ref(), config.intention.as_deref(), config.virtual_cures.as_ref());

    let advice = generate_advice(&annual_chart, &kua_profile, &quantum, &formations);

    // 9. Advanced Schools (San He, Qi Men Dun Jia)
    let san_he = Some(analyze_san_he(config.facing_degrees, None));
    let qimen = Some(calculate_qimen(current_year, current_month, current_day, config.birth_hour.unwrap_or(12)));

    // 10. Period 9 Compliance Check
    let mut p9_compliance = Vec::new();
    if annual_chart.period == 9 {
         p9_compliance.push("Period 9 in effect.".to_string());
         // Check for primary Wealth (9) and Future Wealth (1)
         for p in &annual_chart.palaces {
             if p.water_star == 9 { p9_compliance.push(format!("Primary Wealth Star 9 in {}.", p.sector)); }
             if p.mountain_star == 9 { p9_compliance.push(format!("Primary Health Star 9 in {}.", p.sector)); }
             if p.water_star == 1 { p9_compliance.push(format!("Future Wealth Star 1 in {}.", p.sector)); }
         }
    } else {
        p9_compliance.push(format!("Current Period: {}. Prepare for Period 9 transition.", annual_chart.period));
    }

    Ok(FengShuiReport {
        bazi: bazi_profile,
        kua: kua_profile,
        house_kua,
        hexagram,
        annual_chart,
        replacement_chart,
        yearly_afflictions,
        monthly_chart,
        daily_chart,
        formations,
        quantum,
        advice,
        san_he,
        qimen,
        period_9_compliance: p9_compliance,
    })
}

// === LOGIC IMPLEMENTATION ===

/// Calculates the Four Pillars of Destiny (BaZi).
///
/// Uses astronomical solar terms to determine the exact boundaries of months.
/// If `session` is provided, adds "Quantum Flux" analysis.
pub fn calculate_bazi(year: i32, month: u32, day: u32, hour: u32, session: Option<&SimulationSession>) -> Result<BaZiProfile> {
    if month < 1 || month > 12 { anyhow::bail!("Invalid month: {}", month); }
    if day < 1 || day > 31 { anyhow::bail!("Invalid Day"); }
    // Check NaiveDate validity
    if NaiveDate::from_ymd_opt(year, month, day).is_none() { anyhow::bail!("Invalid date: {}-{}-{}", year, month, day); }

    // Calculate Solar Term to find true Month Branch
    let term_idx = get_solar_term(year, month, day);
    // Rough mapping: Term 0 (Spring Equinox) ~ Month 2 (Rabbit).
    // This formula aligns term index to branch index (0=Rat, 1=Ox...)
    let month_branch_idx = ((term_idx + 2) / 2 + 2) % 12;

    // Year Pillar Calculation
    // Base year 1924 is Jia Zi (Wood Rat)
    let year_offset = (year - 1924).rem_euclid(60);
    let year_stem_idx = year_offset.rem_euclid(10) as usize;
    let year_branch_idx = year_offset.rem_euclid(12) as usize;
    let year_pillar = format!("{} {}", get_stem(year_stem_idx), get_branch(year_branch_idx));

    // Month Pillar Calculation
    // Uses the "Five Tigers Chasing" method based on Year Stem
    let month_start_stem = (year_stem_idx as u32 % 5 * 2 + 2) % 10;
    // Month branch starts at Tiger (idx 2)
    let month_offset_from_tiger = (month_branch_idx + 12 - 2) % 12;
    let month_stem_idx = (month_start_stem + month_offset_from_tiger) % 10;
    let month_pillar = format!("{} {}", get_stem(month_stem_idx as usize), get_branch(month_branch_idx as usize));

    // Day Pillar Calculation
    // Requires counting days from a reference point (Jan 1 2000)
    let base2000 = NaiveDate::from_ymd_opt(2000, 1, 1).unwrap();
    let days = (NaiveDate::from_ymd_opt(year, month, day).unwrap() - base2000).num_days();
    // Reference offset for 2000-01-01
    let day_stem_idx = (4 + days).rem_euclid(10) as usize;
    let day_branch_idx = (6 + days).rem_euclid(12) as usize;
    let day_pillar = format!("{} {}", get_stem(day_stem_idx), get_branch(day_branch_idx));

    // Hour Pillar Calculation
    // Uses "Five Rats Chasing" method based on Day Stem
    let hour_branch_idx = ((hour + 1) / 2).rem_euclid(12) as usize;
    let hour_start_stem = (day_stem_idx as u32 % 5 * 2) % 10;
    let hour_stem_idx = (hour_start_stem + hour_branch_idx as u32) % 10;
    let hour_pillar = format!("{} {}", get_stem(hour_stem_idx as usize), get_branch(hour_branch_idx));

    // Quantum Additions
    let mut quantum_flux = None;
    let mut alternate_pillars = None;

    if let Some(sess) = session {
        // Real-time Flux: Simulate current energy boosting specific elements
        let elements = vec!["Wood", "Fire", "Earth", "Metal", "Water"];
        let flux_element = sess.simulate_decision(&elements.iter().map(|s| s.to_string()).collect::<Vec<_>>(), None, 20).winner;
        quantum_flux = Some(format!("Quantum Field is currently amplifying: {}.", flux_element));

        // Probabilistic Birth: Simulate 'what if' the user was born +/- 1 hour (changing the pillar)
        // Simplified: Just randomize one alternate hour pillar
        let alt_hour_offset = if sess.simulate_decision(&vec!["+".to_string(), "-".to_string()], None, 5).winner == "+" { 1 } else { -1 };
        // Recalc hour with offset
        let alt_hour_idx = (hour_branch_idx as i32 + alt_hour_offset).rem_euclid(12) as usize;
        let alt_h_stem_idx = (hour_start_stem + alt_hour_idx as u32) % 10;
        let alt_pillar = format!("{} {}", get_stem(alt_h_stem_idx as usize), get_branch(alt_hour_idx));
        alternate_pillars = Some(vec![format!("Alternate Timeline (Hour {}): {}", if alt_hour_offset > 0 { "+2h" } else { "-2h" }, alt_pillar)]);
    }

    Ok(BaZiProfile {
        year_pillar, month_pillar, day_pillar, hour_pillar,
        day_master: get_stem(day_stem_idx).to_string(),
        favorable_elements: vec!["Solar Term Adjusted".to_string()],
        quantum_flux,
        alternate_pillars,
    })
}

/// Runs the Quantum Simulation part of the report.
///
/// Generates the Qi Heatmap, checks for resonance with user intention,
/// and calculates the efficacy of placed virtual cures.
fn run_quantum_analysis(
    session: &SimulationSession,
    chart: &FlyingStarChart,
    _monthly: Option<&FlyingStarChart>,
    intention: Option<&str>,
    virtual_cures: Option<&Vec<VirtualCure>>,
) -> QuantumAnalysis {
    // 1. Sector Volatility Simulation
    let sectors = vec!["North", "NE", "East", "SE", "South", "SW", "West", "NW", "Center"];
    let report = session.simulate_decision(&sectors.iter().map(|s| s.to_string()).collect::<Vec<_>>(), None, 100);
    let volatility = 0.5; // Placeholder for calculated entropy variance

    // 2. Automated Cure Suggestions
    let mut cures = Vec::new();
    for p in &chart.palaces {
        let bad_stars = [2, 5]; // 2 Black (Sickness), 5 Yellow (Misfortune)
        if bad_stars.contains(&p.mountain_star) || bad_stars.contains(&p.water_star) {
            cures.push(CureSuggestion {
                sector: p.sector.clone(),
                affliction: "Sickness/Misfortune Star".to_string(),
                cure_name: "Metal Cure (Wu Lou)".to_string(),
                placement_location: "Corner".to_string(),
                success_probability: 0.75, // Base probability
            });
        }
    }

    // 3. Heatmap Generation
    let mut heatmap = vec![vec![0.0; 3]; 3];
    // Base heatmap values derived from Star 8 and 9 (Wealth Stars)
    for p in &chart.palaces {
        let val = if p.water_star == 9 { 1.0 } else if p.water_star == 8 { 0.5 } else { 0.1 };
        // Map Sector Name to Grid Coordinates (3x3 Matrix)
        // Note: Row 0 is South (Up in Feng Shui), Row 2 is North (Down)
        let coords = match p.sector.as_str() {
            "Center" => (1,1), "NW" => (2,2), "W" => (1,2), "NE" => (2,0),
            "S" => (0,1), "N" => (2,1), "SW" => (0,2), "E" => (1,0), "SE" => (0,0),
             _ => (1,1)
        };
        heatmap[coords.0][coords.1] = val;
    }

    // 4. Virtual Cure Impact
    let mut cure_efficacy = 0.0;
    if let Some(vc_list) = virtual_cures {
        for vc in vc_list {
            let r = vc.y.floor() as usize;
            let c = vc.x.floor() as usize;
            if r < 3 && c < 3 {
                 // Cures boost the local sector energy
                 heatmap[r][c] += 0.5;
                 cure_efficacy += 0.1;
            }
        }
    }

    QuantumAnalysis {
        volatility_index: volatility,
        focus_sector: report.winner,
        anomalies: vec![],
        intention_resonance: intention.map(|s| s.to_string()),
        suggested_cures: cures,
        qi_flow: None,
        qi_heatmap: Some(heatmap),
        cure_efficacy: Some(cure_efficacy),
    }
}

/// Calculates the User's Life Gua (Kua) number based on birth year and gender.
pub fn calculate_kua_profile(year: i32, gender: &str) -> KuaProfile {
    let mut sum = 0;
    // Sum digits of year
    let digits: Vec<u32> = year.to_string().chars().filter_map(|c| c.to_digit(10)).collect();
    for d in digits { sum += d as i32; }

    // Reduce to single digit
    while sum > 9 {
        let s_str = sum.to_string();
        sum = 0;
        for c in s_str.chars() {
            sum += c.to_digit(10).unwrap() as i32;
        }
    }

    // Apply gender-specific formula
    let k = if gender == "M" {
        let mut val = 11 - sum;
        while val > 9 { val -= 9; }
        if val == 0 { 9 } else if val == 5 { 2 } else { val }
    } else {
        let mut val = 4 + sum;
        while val > 9 { val -= 9; }
        if val == 5 { 8 } else { val }
    };

    let group = if [1, 3, 4, 9].contains(&k) { "East Group".to_string() } else { "West Group".to_string() };

    let element = match k {
        1 => "Water",
        2 | 8 => "Earth",
        3 | 4 => "Wood",
        6 | 7 => "Metal",
        9 => "Fire",
        _ => "Earth",
    }.to_string();

    let dirs = match k {
        1 => vec![("SE", "Sheng Chi"), ("E", "Tian Yi"), ("S", "Yan Nian"), ("N", "Fu Wei")],
        2 => vec![("NE", "Sheng Chi"), ("W", "Tian Yi"), ("NW", "Yan Nian"), ("SW", "Fu Wei")],
        3 => vec![("S", "Sheng Chi"), ("N", "Tian Yi"), ("SE", "Yan Nian"), ("E", "Fu Wei")],
        4 => vec![("N", "Sheng Chi"), ("S", "Tian Yi"), ("E", "Yan Nian"), ("SE", "Fu Wei")],
        6 => vec![("W", "Sheng Chi"), ("NE", "Tian Yi"), ("SW", "Yan Nian"), ("NW", "Fu Wei")],
        7 => vec![("NW", "Sheng Chi"), ("SW", "Tian Yi"), ("NE", "Yan Nian"), ("W", "Fu Wei")],
        8 => vec![("SW", "Sheng Chi"), ("NW", "Tian Yi"), ("W", "Yan Nian"), ("NE", "Fu Wei")],
        9 => vec![("E", "Sheng Chi"), ("SE", "Tian Yi"), ("N", "Yan Nian"), ("S", "Fu Wei")],
        _ => vec![],
    };

    KuaProfile {
        number: k,
        group,
        element,
        lucky_directions: dirs.into_iter().map(|(a,b)| (a.to_string(), b.to_string())).collect(),
    }
}

/// Calculates the House Kua based on Sitting Direction (opposite of Facing).
pub fn calculate_house_kua(sitting_deg: f64) -> KuaProfile {
    let d = (sitting_deg + 360.0) % 360.0;
    let (num, trigram) = if d >= 337.5 || d < 22.5 { (1, "Kan (Water)") }
    else if d < 67.5 { (8, "Gen (Mountain)") }
    else if d < 112.5 { (3, "Zhen (Thunder)") }
    else if d < 157.5 { (4, "Xun (Wind)") }
    else if d < 202.5 { (9, "Li (Fire)") }
    else if d < 247.5 { (2, "Kun (Earth)") }
    else if d < 292.5 { (7, "Dui (Lake)") }
    else { (6, "Qian (Heaven)") };

    let group = if [1, 3, 4, 9].contains(&num) { "East Group".to_string() } else { "West Group".to_string() };

    KuaProfile {
        number: num,
        group,
        element: trigram.to_string(),
        lucky_directions: vec![],
    }
}

/// Calculates the Hexagram based on specific degree (Xuan Kong Da Gua).
/// Map 360 degrees to 64 Hexagrams.
pub fn calculate_hexagram(degrees: f64) -> HexagramInfo {
    let idx = (degrees / 5.625).floor() as usize % 64;
    HexagramInfo {
        name: "Hexagram".to_string(), // Full list omitted for brevity
        index: idx + 1,
        meaning: "Auspicious alignment".to_string(),
        element: "Unknown".to_string(),
    }
}

/// Core Flying Star Logic.
///
/// Determines the Time Star (Period), Mountain Star (Sitting), and Water Star (Facing).
pub fn calculate_flying_star_chart(construction_year: i32, degrees: f64, current_year: i32, mutation: Option<&SimulationSession>) -> FlyingStarChart {
    let period = get_period(construction_year);
    // Determine 24 Mountain for Facing and Sitting
    let (facing_sector, facing_mountain_idx, _) = get_24_mountain(degrees);
    let (sitting_sector, sitting_mountain_idx, _) = get_24_mountain((degrees + 180.0) % 360.0);

    let facing_label = format!("{} ({})", facing_sector, get_mountain_name(&facing_sector, facing_mountain_idx));
    let sitting_label = format!("{} ({})", sitting_sector, get_mountain_name(&sitting_sector, sitting_mountain_idx));

    // 1. Fly Base Star (Period Star)
    let base_chart = fly_stars(period, true, mutation);

    let sector_map = |s: &str| match s {
        "Center" => 0, "NW" => 1, "W" => 2, "NE" => 3, "S" => 4,
        "N" => 5, "SW" => 6, "E" => 7, "SE" => 8, _ => 0
    };

    let sit_base_star = base_chart[sector_map(&sitting_sector)];
    let face_base_star = base_chart[sector_map(&facing_sector)];

    // 2. Fly Mountain Star (Health)
    let mtn_flight_pol = get_flight_polarity(sit_base_star, sitting_mountain_idx);
    let mtn_chart = fly_stars(sit_base_star, mtn_flight_pol, mutation);

    // 3. Fly Water Star (Wealth)
    let wtr_flight_pol = get_flight_polarity(face_base_star, facing_mountain_idx);
    let wtr_chart = fly_stars(face_base_star, wtr_flight_pol, mutation);

    // 4. Fly Annual Star (Time)
    let annual_star = calculate_annual_star(current_year);
    let annual_chart = fly_stars(annual_star, true, mutation);

    let sectors_ordered = vec!["Center", "NW", "W", "NE", "S", "N", "SW", "E", "SE"];
    let mut palaces = Vec::new();
    for i in 0..9 {
        palaces.push(Palace {
            sector: sectors_ordered[i].to_string(),
            base_star: base_chart[i],
            mountain_star: mtn_chart[i],
            water_star: wtr_chart[i],
            visiting_star: annual_chart[i],
        });
    }

    FlyingStarChart {
        period,
        label: format!("Period {} / Annual {}", period, annual_star),
        facing_mountain: facing_label,
        sitting_mountain: sitting_label,
        palaces,
    }
}

/// Calculates "Ti Gua" (Replacement Stars) if degrees are near a Void Line (Kung Wang).
pub fn calculate_replacement_chart(construction_year: i32, degrees: f64, current_year: i32, mutation: Option<&SimulationSession>) -> Option<FlyingStarChart> {
    let d = degrees % 360.0;
    let mut needs_replacement = false;
    // Check boundaries of 24 Mountains
    for k in 0..24 {
        let boundary = 7.5 + (k as f64 * 15.0);
        if (d - boundary).abs() < 2.0 {
            needs_replacement = true;
            break;
        }
    }
    if needs_replacement {
        // Simplified Replacement Logic: Re-run chart generation then modify stars based on I Ching constants
        let mut chart = calculate_flying_star_chart(construction_year, degrees, current_year, mutation);
        chart.label = "Replacement Chart (Ti Gua)".to_string();
        for palace in &mut chart.palaces {
            // Apply arbitrary replacement logic for demonstration
            if palace.mountain_star != 5 {
                palace.mountain_star = if palace.mountain_star % 2 == 0 { palace.mountain_star - 1 } else { palace.mountain_star + 1 };
                if palace.mountain_star < 1 { palace.mountain_star = 9; }
                if palace.mountain_star > 9 { palace.mountain_star = 1; }
            }
            if palace.water_star != 5 {
                palace.water_star = if palace.water_star % 2 == 0 { palace.water_star + 1 } else { palace.water_star - 1 };
                if palace.water_star < 1 { palace.water_star = 9; }
                if palace.water_star > 9 { palace.water_star = 1; }
            }
        }
        return Some(chart);
    }
    None
}

/// Calculates annual afflictions: Tai Sui, Sui Po, San Sha.
pub fn calculate_yearly_afflictions(year: i32, facing_deg: f64) -> Vec<String> {
    let mut afflictions = Vec::new();
    let zodiac_idx = (year - 1900).rem_euclid(12);
    // Tai Sui (Grand Duke Jupiter) occupies the zodiac direction of the year
    let tai_sui_deg = match zodiac_idx {
        0 => 0.0, 1 => 30.0, 2 => 60.0, 3 => 90.0, 4 => 120.0, 5 => 150.0,
        6 => 180.0, 7 => 210.0, 8 => 240.0, 9 => 270.0, 10 => 300.0, 11 => 330.0, _ => 0.0,
    };
    let diff = (facing_deg - tai_sui_deg).abs();
    if diff < 15.0 || diff > 345.0 {
        afflictions.push(format!("Facing Tai Sui ({} deg): Avoid renovation.", tai_sui_deg));
    }
    // Sui Po (Year Breaker) is opposite Tai Sui
    let sui_po_deg = (tai_sui_deg + 180.0) % 360.0;
    let diff_sp = (facing_deg - sui_po_deg).abs();
    if diff_sp < 15.0 || diff_sp > 345.0 {
        afflictions.push("Facing Sui Po (Year Breaker): High risk if disturbed.".to_string());
    }
    // San Sha (Three Killings) depends on the Trinity (San He) frame
    let san_sha_dir = match zodiac_idx % 4 {
        0 => "South", 1 => "East", 2 => "North", 3 => "West", _ => "None",
    };
    afflictions.push(format!("San Sha (Three Killings) is in the {} this year.", san_sha_dir));
    afflictions
}

/// Calculates the Monthly Flying Star chart.
pub fn calculate_monthly_chart(year: i32, month: u32, mutation: Option<&SimulationSession>) -> Option<FlyingStarChart> {
    let offset = (year - 1900).rem_euclid(12);
    // Base stars pattern for months (Tiger/Monkey/Snake/Pig years etc)
    let start_star = if [0, 6, 3, 9].contains(&offset) { 8 }
    else if [1, 7, 4, 10].contains(&offset) { 5 }
    else { 2 };
    let chinese_month_idx = if month == 1 { 12 } else { month - 1 };
    let mut ruling_star = start_star - (chinese_month_idx as i32 - 1);
    while ruling_star < 1 { ruling_star += 9; }
    while ruling_star > 9 { ruling_star -= 9; }
    let chart_nums = fly_stars(ruling_star, true, mutation);
    let sectors_ordered = vec!["Center", "NW", "W", "NE", "S", "N", "SW", "E", "SE"];
    let mut palaces = Vec::new();
    for i in 0..9 {
        palaces.push(Palace {
            sector: sectors_ordered[i].to_string(),
            base_star: 0, mountain_star: 0, water_star: 0,
            visiting_star: chart_nums[i],
        });
    }
    Some(FlyingStarChart {
        period: ruling_star, label: format!("Month {}", month),
        facing_mountain: "-".to_string(), sitting_mountain: "-".to_string(), palaces,
    })
}

/// Calculates the Daily Flying Star chart.
///
/// Accounts for Yin/Yang cycles based on Winter/Summer Solstices.
pub fn calculate_daily_chart(year: i32, month: u32, day: u32, mutation: Option<&SimulationSession>) -> Option<FlyingStarChart> {
    let d = NaiveDate::from_ymd_opt(year, month, day)?;
    let winter_solstice = NaiveDate::from_ymd_opt(year, 12, 21)?;
    let summer_solstice = NaiveDate::from_ymd_opt(year, 6, 21)?;
    // If between Summer and Winter, flow is Yin (descending)
    let is_yin = (d >= summer_solstice) && (d < winter_solstice);
    let days_diff = if is_yin { (d - summer_solstice).num_days() } else {
        let ws_prev = NaiveDate::from_ymd_opt(if month < 6 { year - 1 } else { year }, 12, 21)?;
        (d - ws_prev).num_days()
    };
    let base_star = if is_yin {
        let mut s = 9 - (days_diff % 9); if s < 1 { s += 9; } s as i32
    } else {
        let mut s = 1 + (days_diff % 9); if s > 9 { s -= 9; } s as i32
    };
    let chart_nums = fly_stars(base_star, true, mutation);
    let sectors_ordered = vec!["Center", "NW", "W", "NE", "S", "N", "SW", "E", "SE"];
    let mut palaces = Vec::new();
    for i in 0..9 {
        palaces.push(Palace {
            sector: sectors_ordered[i].to_string(),
            base_star: 0, mountain_star: 0, water_star: 0,
            visiting_star: chart_nums[i],
        });
    }
    Some(FlyingStarChart {
        period: base_star, label: format!("Day {}", day),
        facing_mountain: "-".to_string(), sitting_mountain: "-".to_string(), palaces,
    })
}

/// Analyzes special auspicious formations in the chart.
pub fn analyze_formations(chart: &FlyingStarChart) -> Vec<String> {
    let mut formations = Vec::new();
    let mut sum_ten_water = true;
    let mut sum_ten_mountain = true;
    let mut pearl_string = true;
    let mut parent_string = true;
    for p in &chart.palaces {
        // Sum of Ten: Base + Star = 10
        if p.base_star + p.water_star != 10 { sum_ten_water = false; }
        if p.base_star + p.mountain_star != 10 { sum_ten_mountain = false; }
        // Parent String: Stars from same triplet (1-4-7, 2-5-8, 3-6-9)
        let stars = vec![p.base_star, p.mountain_star, p.water_star];
        let mods: Vec<i32> = stars.iter().map(|s| s % 3).collect();
        if !(mods[0] == mods[1] && mods[1] == mods[2]) { parent_string = false; }
        // Pearl String: Consecutive numbers (e.g., 1-2-3)
        let mut sorted = stars.clone(); sorted.sort();
        if !((sorted[1] == sorted[0] + 1) && (sorted[2] == sorted[1] + 1)) { pearl_string = false; }
    }
    if sum_ten_water { formations.push("Sum of Ten (Water): Great wealth potential.".to_string()); }
    if sum_ten_mountain { formations.push("Sum of Ten (Mountain): Great health/relationship potential.".to_string()); }
    if parent_string { formations.push("Parent String: Auspicious connectivity across all sectors.".to_string()); }
    if pearl_string { formations.push("Pearl String: Smooth Qi flow.".to_string()); }
    formations.push("Check Castle Gate sectors for alternative wealth activation.".to_string());
    formations
}

/// Generates actionable advice based on Stars + Kua + Quantum analysis.
pub fn generate_advice(chart: &FlyingStarChart, kua: &Option<KuaProfile>, quantum: &QuantumAnalysis, formations: &Vec<String>) -> Vec<String> {
    let mut advice = Vec::new();
    // Period 9 Wealth Star is 9, Period 8 was 8
    let wealth_star = if chart.period == 9 { 9 } else { 8 };
    for p in &chart.palaces {
        if p.water_star == wealth_star { advice.push(format!("Sector {} contains the Water Star {}, activating Wealth Luck.", p.sector, wealth_star)); }
        if p.mountain_star == wealth_star { advice.push(format!("Sector {} contains the Mountain Star {}, good for Health/Relations.", p.sector, wealth_star)); }
    }
    if let Some(k) = kua { advice.push(format!("Your Life Gua is {}. Strongest direction: {}.", k.number, k.lucky_directions[0].0)); }
    advice.push(format!("Quantum Focus: {}. Volatility: {:.2}", quantum.focus_sector, quantum.volatility_index));
    if !formations.is_empty() { advice.push("Special Auspicious Formations detected! See report details.".to_string()); }
    advice
}

// === UTILS ===

/// Determines the Feng Shui Period (1-9) based on year.
fn get_period(year: i32) -> i32 {
    match year {
        y if y < 1864 => 1, y if y <= 1883 => 1, y if y <= 1903 => 2, y if y <= 1923 => 3,
        y if y <= 1943 => 4, y if y <= 1963 => 5, y if y <= 1983 => 6, y if y <= 2003 => 7,
        y if y <= 2023 => 8, _ => 9,
    }
}

fn calculate_annual_star(year: i32) -> i32 {
    let mut sum = 0;
    let digits: Vec<u32> = year.to_string().chars().filter_map(|c| c.to_digit(10)).collect();
    for d in digits { sum += d as i32; }
    while sum > 9 {
        let s_str = sum.to_string(); sum = 0;
        for c in s_str.chars() { sum += c.to_digit(10).unwrap() as i32; }
    }
    let mut star = 11 - sum;
    while star > 9 { star -= 9; }
    if star == 0 { star = 9; }
    star
}

/// The Lo Shu Flight Path algorithm.
///
/// Moves numbers through the 9 sectors in a specific order: Center -> NW -> W -> NE -> S -> N -> SW -> E -> SE.
/// If `mutation` is active, entropy can flip the flight direction or value.
fn fly_stars(center_star: i32, forward: bool, mutation: Option<&SimulationSession>) -> Vec<i32> {
    let mut chart = vec![0; 9];
    let mut current = center_star;
    let path = vec![0, 1, 2, 3, 4, 5, 6, 7, 8]; // Lo Shu path indices
    for &idx in &path {
        let mut val = current;
        if let Some(session) = mutation {
             // Quantum check: does this star "mutate"?
             let outcome = session.simulate_decision(&vec!["Normal".to_string(), "Mutate".to_string()], None, 10);
             if outcome.winner == "Mutate" {
                 // Flip value up or down
                 if session.simulate_decision(&vec!["+".to_string(), "-".to_string()], None, 5).winner == "+" { val += 1; } else { val -= 1; }
                 if val > 9 { val = 1; } if val < 1 { val = 9; }
             }
        }
        chart[idx] = val;
        if forward { current += 1; if current > 9 { current = 1; } }
        else { current -= 1; if current < 1 { current = 9; } }
    }
    chart
}

/// Determines if a star flies forward (Yang) or backward (Yin).
///
/// Depends on parity of the star and the yin/yang nature of the house mountain.
fn get_flight_polarity(star: i32, house_mtn_idx: usize) -> bool {
    if star == 5 { return true; } // Star 5 follows special rules (usually matches house/period polarity)
    let pattern_odd = [true, false, false]; // Yang, Yin, Yin
    let pattern_even = [false, true, true]; // Yin, Yang, Yang
    let is_even = star % 2 == 0;
    if is_even { pattern_even[house_mtn_idx - 1] } else { pattern_odd[house_mtn_idx - 1] }
}

/// Maps a degree (0-360) to one of the 24 Mountains.
///
/// Returns: (Mountain Name, Index 1-3, Is_Yang)
fn get_24_mountain(deg: f64) -> (String, usize, bool) {
    let d = (deg % 360.0 + 360.0) % 360.0;
    // North
    if d >= 337.5 && d < 352.5 { return ("N".to_string(), 1, true); } // Ren
    if d >= 352.5 || d < 7.5   { return ("N".to_string(), 2, false); } // Zi
    if d >= 7.5 && d < 22.5    { return ("N".to_string(), 3, false); } // Gui
    // Northeast
    if d >= 22.5 && d < 37.5   { return ("NE".to_string(), 1, false); } // Chou
    if d >= 37.5 && d < 52.5   { return ("NE".to_string(), 2, true); }  // Gen
    if d >= 52.5 && d < 67.5   { return ("NE".to_string(), 3, true); }  // Yin
    // East
    if d >= 67.5 && d < 82.5   { return ("E".to_string(), 1, true); }   // Jia
    if d >= 82.5 && d < 97.5   { return ("E".to_string(), 2, false); }  // Mao
    if d >= 97.5 && d < 112.5  { return ("E".to_string(), 3, false); }  // Yi
    // Southeast
    if d >= 112.5 && d < 127.5 { return ("SE".to_string(), 1, false); } // Chen
    if d >= 127.5 && d < 142.5 { return ("SE".to_string(), 2, true); }  // Xun
    if d >= 142.5 && d < 157.5 { return ("SE".to_string(), 3, true); }  // Si
    // South
    if d >= 157.5 && d < 172.5 { return ("S".to_string(), 1, true); }   // Bing
    if d >= 172.5 && d < 187.5 { return ("S".to_string(), 2, false); }  // Wu
    if d >= 187.5 && d < 202.5 { return ("S".to_string(), 3, false); }  // Ding
    // Southwest
    if d >= 202.5 && d < 217.5 { return ("SW".to_string(), 1, false); } // Wei
    if d >= 217.5 && d < 232.5 { return ("SW".to_string(), 2, true); }  // Kun
    if d >= 232.5 && d < 247.5 { return ("SW".to_string(), 3, true); }  // Shen
    // West
    if d >= 247.5 && d < 262.5 { return ("W".to_string(), 1, true); }   // Geng
    if d >= 262.5 && d < 277.5 { return ("W".to_string(), 2, false); }  // You
    if d >= 277.5 && d < 292.5 { return ("W".to_string(), 3, false); }  // Xin
    // Northwest
    if d >= 292.5 && d < 307.5 { return ("NW".to_string(), 1, false); } // Xu
    if d >= 307.5 && d < 322.5 { return ("NW".to_string(), 2, true); }  // Qian
    if d >= 322.5 && d < 337.5 { return ("NW".to_string(), 3, true); }  // Hai

    // Default fallback
    ("N".to_string(), 2, false)
}

fn get_mountain_name(sector: &str, idx: usize) -> &'static str {
    match (sector, idx) {
        ("N", 1) => "Ren", ("N", 2) => "Zi", ("N", 3) => "Gui",
        ("NE", 1) => "Chou", ("NE", 2) => "Gen", ("NE", 3) => "Yin",
        ("E", 1) => "Jia", ("E", 2) => "Mao", ("E", 3) => "Yi",
        ("SE", 1) => "Chen", ("SE", 2) => "Xun", ("SE", 3) => "Si",
        ("S", 1) => "Bing", ("S", 2) => "Wu", ("S", 3) => "Ding",
        ("SW", 1) => "Wei", ("SW", 2) => "Kun", ("SW", 3) => "Shen",
        ("W", 1) => "Geng", ("W", 2) => "You", ("W", 3) => "Xin",
        ("NW", 1) => "Xu", ("NW", 2) => "Qian", ("NW", 3) => "Hai",
        _ => "Unknown"
    }
}
